vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        uploads:
            uri_prefix: /img/
            upload_destination: '%kernel.project_dir%/public/img'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
